services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - app_network

  app:
    build: ./app
    container_name: python_app
    depends_on:
      - db
    env_file: .env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
